// Generated 2015-11-06 01:38:51 -0500

const int CRATTLECRUTE_BACK_FOOT_PNG_OFFSET = 0;
const int CRATTLECRUTE_BACK_FOOT_PNG_SIZE = 2603;
const int CRATTLECRUTE_BACK_FOOT_PNG_INFO_OFFSET = 2603;
const int CRATTLECRUTE_BACK_FOOT_PNG_INFO_SIZE = 71;
const int CRATTLECRUTE_BODY_PNG_OFFSET = 2674;
const int CRATTLECRUTE_BODY_PNG_SIZE = 1539;
const int CRATTLECRUTE_BODY_PNG_INFO_OFFSET = 4213;
const int CRATTLECRUTE_BODY_PNG_INFO_SIZE = 50;
const int CRATTLECRUTE_FRONT_FOOT_PNG_OFFSET = 4263;
const int CRATTLECRUTE_FRONT_FOOT_PNG_SIZE = 2710;
const int CRATTLECRUTE_FRONT_FOOT_PNG_INFO_OFFSET = 6973;
const int CRATTLECRUTE_FRONT_FOOT_PNG_INFO_SIZE = 71;
const int EYES_STANDARD_EYE_PNG_OFFSET = 7044;
const int EYES_STANDARD_EYE_PNG_SIZE = 165;
const int TERRAIN_DIRT1_PNG_OFFSET = 7209;
const int TERRAIN_DIRT1_PNG_SIZE = 270;
